# Generated by Django 5.0.1 on 2024-01-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('information', models.TextField(blank=True, null=True)),
                ('muallif', models.CharField(max_length=50)),
                ('rasm', models.ImageField(upload_to='kitob_rasmlari/')),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('janri', models.CharField(max_length=100)),
                ('publication_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
