# Generated by Django 5.0.1 on 2024-01-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('muallif', models.CharField(max_length=50)),
                ('janri', models.CharField(max_length=100)),
                ('publication_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
